### ISSUE TITLE
runners for azure with different OS

### ISSUE THREAD

**Issue by binamov** [chef-cft/bjc#441]
automate has the capacity to control what runners run jobs. We can create runners of a different OS and then specify phase filters that instruct for the phase to run on two different OSs. This will run the phases in parallel, allowing us to build AWS and ARM templates at the same time.

**Comment by ChefRycar** [comment]
To ensure I've got a good understanding of what's being proposed here:
As an SA, I'd like to be able to build releases of BJC targeting both AWS and Azure. I can do this with existing configurations, but there will be a significant cost to do so, as there's no way to parallelize the process easily within automate.
With the filters feature, I can define discrete subsets of my environment to act as runners for each platform, and via supported config options, can have those runners execute their associated jobs in parallel, having one set of nodes handle building for AWS, and another building for azure.
To accomplish this today, it will require spinning up runners using a different OS or platform version than existing runners, as those are the filters provided. There's nothing platform-specific that needs to be evaluated, but that's currently the only way to achieve the desired behavior.
In the future, this will likely be better served by introducing additional filters, so that arbitrary platform spreads are not required for subsequent implementations of parallelization, or any other problem that definable groups of runners can solve.

If the above is correct, I'd propose the following actions:
1) MVP: Set up a runner on another operating system. Ensure that it can be used as a target in an ephemeral test pipeline so as not to disrupt bjc builds while implementing.

2) Next, determine *how* we're going to conditionally define build_cookbook activity based on the platform of the runners. NOTE: this is my biggest concern. I think the desired behavior is something we should want, but think the present implementation requires us to write code in our build cookbook that will need to get ripped out later, since per-platform behavior isn't really what's desired here, but per-publish-target behavior. 

3) Add the conditional logic to our build cookbook to trigger azure builds on one set of nodes, and aws builds on another. Confirm that they do indeed run in parallel.

See the above as three separate issues at the least to keep the units of work manageable. Thoughts?

**Comment by binamov** [comment]
@ChefRycar all accurate, except that: 
1. we MVP on the real pipeline, i've already tested filters in a clean env
2. we will add `case` statements to the relevant phases where we'll check for conditions of `os` AND a tag to match azure/aws and use that to branch different builds. As for ripping it out later, the dev team hasn't indicated that they will expand filters any time soon.
3. yup.

**Comment by ChefRycar** [comment]
Okay, cool. I think so long as we're cognizant of the changes we may want to make down the road, my concern is well covered. Just wanted to make sure I wrote it down somewhere so I'm not scratching my head in 6 months about why my builders care if they're running on ubuntu or centos. :-)

Last question: would the desire be for those runners to live in amazon still, or would azure be preferred? Not sure if it matters from a post-build perspective, but would prefer AWS if not for MVP, just to keep variables manageable in the short term. (I have no idea what, if any, network/firewall/etc considerations I should make creating an Azure runner, and we'd probably want to define those if we want them to live there)

**Comment by binamov** [comment]
yeah stick with AWS @ChefRycar for now just need a couple of runners with a different `os` to validate.

**Comment by binamov** [comment]
I just added https://github.com/chef-cft/bjc/pull/442/commits/1778ab30f41084c96ded09a8c968f18485e951fa and it looks like this:

![parallels](https://cloud.githubusercontent.com/assets/292705/24117795/d51527e4-0d68-11e7-9d44-e2a20c92fcd8.PNG)

@scarolan please review this thread too
