### ISSUE TITLE
add Risk demo script/walkthrough 

### ISSUE THREAD

**Issue by binamov** [chef-cft/bjc#558]

**Comment by joderita** [comment]
Consider moving Compliance portion of script ("look at these profiles!") to after the delivery review?

**Comment by joderita** [comment]
Depending on how the bjc-ecommerce build-cookbook is designed (with Acceptance going all green or just 1/4 green), modify the script to address why we did it this way and what the customer won't be seeing as part of the demo.

"You'll only see one of our four nodes go green because blah"
or
"You'll see all four of our nodes come back green because we cheated"

**Comment by binamov** [comment]
We have a https://github.com/chef-cft/bjc/blob/master/SSL_Demo_Script.md and so it probably needs to be deprecated as port of this work, and instead we should get like a Risk_demo_script.md

**Comment by scarolan** [comment]
I ran through the 3.0.0 demo and all four nodes compliance status turn up green as soon as 'Verify' is done running.  I don't think you need to mention it at all.  Just don't show the green ring until the very end of your demo story, then you don't need to say you 'cheated'.  BTW, it's not cheating, it's a custom configuration to illustrate how the pipeline works in a short amount of time.

**Comment by binamov** [comment]
fixed in #580
